

library(readr)        # to import tabular data (e.g. csv)
library(dplyr)        # to manipulate (tabular) data
library(ggplot2)      # to visualize data
library(sf)           # to handle spatial vector data
library(terra)        # To handle raster data
library(lubridate)
library(zoo)
library(scales)


wildschwein_BE <- read_delim("wildschwein_BE_2056.csv",",") # adjust path

wildschwein_BE <- st_as_sf(wildschwein_BE, coords = c("E", "N"), crs = 2056, remove = FALSE)

#################################################################################

#Task 1
wildschwein_BE <- group_by(wildschwein_BE,TierID)

wildschwein_BE$timelag  <- as.numeric(difftime(lead(wildschwein_BE$DatetimeUTC), wildschwein_BE$DatetimeUTC))
wildschwein_BE$timelag  <- as.numeric(difftime(lead(wildschwein_BE$DatetimeUTC), wildschwein_BE$DatetimeUTC),units = "secs")


as.integer(wildschwein_BE$timelag)

wildschwein_BE %>% 
  group_by(TierID) %>%
  summarise(
    mean_timelag=mean(timelag, na.rm=T)
  )

#questions 
unique(wildschwein_BE$TierName)
unique(wildschwein_BE$TierID)

ggplot(wildschwein_BE, aes(x=wildschwein_BE$DatetimeUTC, y=wildschwein_BE$TierID)) +
  geom_line()

range_002A=range(wildschwein_BE$DatetimeUTC[wildschwein_BE$TierID=="002A"])
range_016A=range(wildschwein_BE$DatetimeUTC[wildschwein_BE$TierID=="016A"])
range_018A=range(wildschwein_BE$DatetimeUTC[wildschwein_BE$TierID=="018A"])



##################################################################################

#Task 2


euc.dist <- function(x1, x2) sqrt(sum((x1 - x2) ^ 2))
euc.dist <- function(E,N) sqrt(sum((E-lead(E,1))^ 2,(N-lead(N,1))^ 2))
euc.dist = function(x,y) (sqrt((lead(x)-x)^2+(lead(y)-y)^2))


wildschwein_BE$steplength= euc.dist(wildschwein_BE$E, wildschwein_BE$N)


wildschwein_BE$Speed = wildschwein_BE$steplength/wildschwein_BE$timelag

#question
The speed unit is m/s

##################################################################################

#Task 3

caro <- read_delim("caro60.txt",",")
caro <- st_as_sf(caro, coords = c("E", "N"), crs = 2056, remove = FALSE)



caro_3 = caro[seq(from = 1, to = 200, by = 3),]
caro_6 = caro[seq(from = 1, to = 200, by = 6),]
caro_9 = caro[seq(from = 1, to = 200, by = 9),]

nrow(caro)
nrow(caro_3)
nrow(caro_6)
nrow(caro_9)


caro$timelag  <- as.numeric(difftime(lead(caro$DatetimeUTC), caro$DatetimeUTC),units = "secs")
caro$steplength= euc.dist(caro$E, caro$N)
caro$Speed = caro$steplength/caro$timelag

#caro_3
caro_3$timelag  <- as.numeric(difftime(lead(caro_3$DatetimeUTC), caro_3$DatetimeUTC),units = "secs")
caro_3$steplength= euc.dist(caro_3$E, caro_3$N)
caro_3$Speed = caro_3$steplength/caro_3$timelag

# caro_6

caro_6$timelag  <- as.numeric(difftime(lead(caro_6$DatetimeUTC), caro_6$DatetimeUTC),units = "secs")
caro_6$steplength= euc.dist(caro_6$E, caro_6$N)
caro_6$Speed = caro_6$steplength/caro_6$timelag

# caro_9
caro_9$timelag  <- as.numeric(difftime(lead(caro_9$DatetimeUTC), caro_9$DatetimeUTC),units = "secs")
caro_9$steplength= euc.dist(caro_9$E, caro_9$N)
caro_9$Speed = caro_9$steplength/caro_9$timelag



caro_13=rbind(caro,caro_3)
caro_13$Trajectory=c(replicate(200, "1 minute"), replicate(67,"3 minutes"))

caro_16=rbind(caro,caro_6)
caro_16$Trajectory=c(replicate(200, "1 minute"), replicate(34,"6 minutes"))

caro_19=rbind(caro,caro_9)
caro_19$Trajectory=c(replicate(200, "1 minute"), replicate(23,"9 minutes"))

caro_all=rbind(caro, caro_3 , caro_6, caro_9)
caro_all$Trajectory=c(replicate(200, "1 minute"), replicate(67,"3 minutes"), replicate(34,"6 minutes"),replicate(23,"9 minutes")  )



ggplot(caro, aes(x=N,y=E, group=Speed)) + geom_point()

ggplot(caro, aes(y=N, x=E, group=1) ) +
  geom_path()+ geom_point()

ggplot(caro_3, aes(y=N, x=E, group=1) ) +
  geom_path()+ geom_point()

ggplot(caro_13, aes(y=N, x=E, col=Trajectory) ) +
  geom_path()+ geom_point()

ggplot(caro_16, aes(y=N, x=E, col=Trajectory) ) +
  geom_path()+ geom_point()

ggplot(caro_19, aes(y=N, x=E, col=Trajectory) ) +
  geom_path()+ geom_point()

ggplot(caro_all, aes(y=N, x=E, col=Trajectory) ) +
  geom_path()+ geom_point()

 
caro_all$Time <- format(as.POSIXlt(caro_all$DatetimeUTC, "%Y-%m-%d %H:%M:%S", tz = "UTC"), format = "%H:%M")
str(caro)

ggplot(caro_all, aes(Time,Speed, col = Trajectory, group = 1)) + geom_line()


caro_all$Time <- format(as.POSIXct(caro_all$DatetimeUTC, "%Y-%m-%d %H:%M:%S", tz = "UTC"), format = "%H:%M")
caro_all$Time = strptime(caro_all$Time, format = "%H:%M" )
caro_all$Time = as.POSIXct(caro_all$Time, format = "%H:%M")

str(caro_all)


ggplot(caro_all, aes(Time,Speed, col = Trajectory, group = 1)) + geom_line() +
  scale_x_datetime(breaks = date_breaks("1 hour"), labels=date_format("%H:%M:%S"))+
  theme_minimal() + ggtitle("Comparing derived speed at different sampling intervals")
 

################################################################################

#Task 4

library(zoo)

example <- rnorm(10)
rollmean(example,k = 3,fill = NA,align = "left")

rollmean(example,k = 4,fill = NA,align = "left")

rollmean(example,k = 6,fill = NA,align = "left")

caro$Speedk3=rollmean(caro$Speed,k = 3,fill = NA,align = "left")
caro$Speedk5=rollmean(caro$Speed,k = 5,fill = NA,align = "left")

library(tidyr)
caro_long <- gather(caro, key = k_value , value = Speed, Speed:Speedk5, factor_key = TRUE) 


caro_long$Time <- format(as.POSIXlt(caro_long$DatetimeUTC, "%Y-%m-%d %H:%M:%S", tz = "UTC"), format = "%H:%M")

caro_long$k_value=as.factor(caro_long$k_value)
caro_long$Time = strptime(caro_long$Time, format = "%H:%M" 
caro_long$Time = as.POSIXct(caro_long$Time, format = "%H:%M")

ggplot(caro_long, aes(Time, Speed,col=k_value, group = 1)) + geom_line()+
  scale_x_datetime(breaks = date_breaks("1 hour"), labels=date_format("%H:%M:%S"))+
  theme_minimal() + ggtitle("Comparing different window sizes (k-values)")
